### ISSUE TITLE
pre-airdrop blitz checklist

### ISSUE THREAD

**Issue by isysd** [guldcoin/ledger-guld#34]
websites TODO List:

 + [x] fix design issues on guld.legal
 + [ ] re-design guld.info with html documents and embedded slideshows
 + [ ] index page for guld.tech
 + [ ] copy & improve buy and claim pages from iramiller.com for GULD sales
 + [ ] publish transaction generator

**Comment by ferdreyfus** [comment]
Announcements and Welcome message for guld.io

https://bitbucket.org/guld/documents-guld/commits/142fa7a2e0e8f0624b985448b8172959322d982a

**Comment by riomyers** [comment]
@ferdreyfus we will be linking the guld.io website to a Reddit announcement once that's posted correct? Please send me the link once you have it and I'll update the site, I have the announcement banner ready to go when we are 😊

**Comment by ferdreyfus** [comment]
Reddit Link to announcement!

https://www.reddit.com/r/guldblocktree/comments/96a7mg/guld_releases_project_updates_and_airdrop/

**Comment by benelsen** [comment]
Not cool.
I've reported this for abuse of TOS (C.3) to github. #244

**Comment by isysd** [comment]
@benelsen I'm sorry you feel that way this was abusive. We are not trying to publish personal data, and this is not really automated.

You contributed to projects we use. We are trying to quantify and reward you for that in the platform you used to make the contribution. If you do not wish to participate, and would PGP sign to that effect, we will gladly delete your profile, which is constructed from your public contribution history.
